spring:
  application:
    name: auth-service
#  main:
#    web-application-type: servlet

#  datasource:
#    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://host.docker.internal:5432/auth_db}
#    username: ${SPRING_DATASOURCE_USERNAME:postgres}
#    password: ${SPRING_DATASOURCE_PASSWORD:0000}
#    driver-class-name: org.postgresql.Driver
#    hikari:
#      maximum-pool-size: 5
#      minimum-idle: 1
#      idle-timeout: 300000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    consul:
      #Use below config for running locally with IDE
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
        #Use below config for running with Docker Compose
#      host: ${CONSUL_HOST:host.docker.internal}
#      port: ${CONSUL_PORT:8500}
      discovery:
        service-name: ${spring.application.name}
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 10s
        instance-id: ${spring.application.name}-${server.port}
        tags:
          - auth-service
          - secure=true

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
